---
title: "EDA Project"
author: "Matthew Wilson"
date: "2025-11-13"
format:
  html:
    code-fold: true
    toc: true
---

## Introduction / motivation of why this project is relevant and interesting

I find it very important to understand how the circumstances of someone's life impacts their health. I am in a human development class where we are learning about how the factors of our lives impact us, both the factors we can and can't control. In this dataset I have the chance to study how a person's race and sex, which they can't control, and a person's educational status, which they can somewhat control, change how likely they were to be killed by covid. Or to see if it in fact has no impact.

## Motivating question (what are you hoping to learn from this data?)
What impact do race, sex, education, and iteractions between the factors have on a person's chance of dying during the covid epidemic? Are any groups impacted by covid more than others in terms of a change in the proportion of deaths?

## Information about how you determined that it was ethical / allowable to get the data that you gathered and/or how you implemented good scraping practice
I knew it was ethical through two processes. First, the data was taken from a government website that states that its purpose is to provide the public with data. The website also provided an API that would allow me to scrape the data. Second, I checked the robots.txt and determined the rules and regulations that were placed on scraping and followed them.


## Summary of the steps needed to get your data with an emphasis on teaching other how they could get started with a similar project
First, I found the webpage that contained the data I wanted and obtained an api that I used to scrape data onto my computer as a json file using the library "requests". Then, I used the pandas library to convert the file into a dataframe. After that, I cleaned my data using regex to condense and clarify values, I dropped rows with unknown values, and I converted certain columns into numeric values so I could do arithmetic with them.
After cleaning the data, I made a new dataset that I can use. This was done by condensing the dataset so that it contained the deaths for both 2019 and 2020 in the same row. I also determined the proportion of deaths (both total and covid) that occured for each age group while grouping by the demographic information. Finally, I also compared how the proportion of total deaths per age group in 2019 compared to the proportion of covid deaths per age group in 2020. This way, my 2019 data acts as a control when I analyze covid deaths.



## Overly detailed accounts are not required (and discouraged)


## Just provide enough info to help someone else potentially get started with a similar project